eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/
server:
  port: 18764

spring:
  application:
    name: service-feign
# feign配置
feign:
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true

